// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NfeSaas.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NfeSaas.Infrastructure.Migrations
{
    [DbContext(typeof(NfeDbContext))]
    partial class NfeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NfeSaas.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmbienteSefaz")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaminhoLogotipo")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<byte[]>("CertificadoBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("CertificadoCnpj")
                        .HasColumnType("text");

                    b.Property<string>("CertificadoSenha")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CertificadoValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CodigoMunicipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("RegimeTributario")
                        .HasColumnType("integer");

                    b.Property<int>("SerieNFCe")
                        .HasColumnType("integer");

                    b.Property<int>("SerieNFe")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UltimoNumeronFCe")
                        .HasColumnType("integer");

                    b.Property<int>("UltimoNumeronFe")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.ItemNotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AliquotaCofins")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AliquotaIcms")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AliquotaIcmsSt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AliquotaIpi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AliquotaPis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseCalculoCofins")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseCalculoIcms")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("BaseCalculoIcmsReducao")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BaseCalculoIcmsSt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseCalculoPis")
                        .HasColumnType("numeric");

                    b.Property<string>("Cest")
                        .HasColumnType("text");

                    b.Property<string>("Cfop")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("CodigoEan")
                        .HasColumnType("text");

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CstCofins")
                        .HasColumnType("integer");

                    b.Property<int>("CstIcms")
                        .HasColumnType("integer");

                    b.Property<string>("CstIpi")
                        .HasColumnType("text");

                    b.Property<int>("CstPis")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroItem")
                        .HasColumnType("integer");

                    b.Property<int>("OrigemMercadoria")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<string>("UnidadeComercial")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorCofins")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("ValorIcms")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("ValorIcmsSt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorIpi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorPis")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("itens_nota_fiscal", (string)null);
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ambiente")
                        .HasColumnType("integer");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinatarioBairro")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioCep")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioCidade")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioCodigoMunicipio")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioComplemento")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioCpfCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("DestinatarioEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DestinatarioInscricaoEstadual")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioLogradouro")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioNumero")
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioRazaoSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("DestinatarioTipoPessoa")
                        .HasColumnType("integer");

                    b.Property<string>("DestinatarioUf")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Finalidade")
                        .HasColumnType("integer");

                    b.Property<string>("FormaPagemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InformacoesAdicionais")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ModalidadeFrete")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Serie")
                        .HasColumnType("integer");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCofins")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDesconto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalFrete")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIcms")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("TotalIcmsSt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalNota")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("TotalOutrasDespesas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalProdutos")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("TotalSeguro")
                        .HasColumnType("numeric");

                    b.Property<string>("TransportadoraCpfCnpj")
                        .HasColumnType("text");

                    b.Property<string>("TransportadoraRazaoSocial")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorPagamento")
                        .HasColumnType("numeric");

                    b.Property<string>("XmlCancelamento")
                        .HasColumnType("text");

                    b.Property<string>("XmlEnvio")
                        .HasColumnType("text");

                    b.Property<string>("XmlRetorno")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAcesso");

                    b.HasIndex("EmpresaId");

                    b.ToTable("notas_fiscais", (string)null);
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.ItemNotaFiscal", b =>
                {
                    b.HasOne("NfeSaas.Domain.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.NotaFiscal", b =>
                {
                    b.HasOne("NfeSaas.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Notas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("NfeSaas.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("NfeSaas.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
